const Courses = [{
        id: "1",
        title: "Englich",
        image: require("../../assets/course/eng.png"),
        description: "English is a West Germanic language of the Indo-European language family, originally spoken by the inhabitants of early medieval England",
        course1: "american",
        course2: "england",
        course3: "Britch",
        price: 2000,
    },
    {
        id: "",
        title: "Math ",
        image: require("../../assets/course/math.jpg"),
        description: "Mathematics is the science that deals with the logic of shape, quantity and arrangement. Math is all around us, in everything we do. ",
        course1: "A",
        course2: "B",
        course3: "C",
        price: 1000,
    },
    {
        id: "3",
        title: "Programming ",
        image: require("../../assets/course/coding.jpg"),
        description: "is the process of creating a set of instructions that tell a computer how to perform a task. Programming can be done using a variety of computer programming languages, such as JavaScript, Python, and C++. ",

        course1: "html",
        course2: "css",
        course3: "javascript",
        price: 5500,
    },
    {
        id: "4",
        title: "chemistry",
        image: require("../../assets/course/che.jpg"),
        description: "Chemistry is the branch of science that deals with the properties, composition, and structure of elements and compounds, how they can change, and the energy that is released or absorbed when they change",
        course1: "A",
        course2: "A+",
        course3: "B",
        price: 3000,
    },
    {
        id: "5",
        title: "Physics",
        image: require("../../assets/course/phy.jpg"),
        description: "Physics is the natural science that studies matter, its fundamental constituents, its motion and behavior through space and time, and the related entities of energy and force. Physics is one of the most fundamental scientific disciplines, with its main goal being to understand how the universe behaves",
        course1: "electrical",
        course2: "Electromagnetic",
        course3: "induction",
        price: 2500,
    },
    {
        id: "6",
        title: "Biology",
        image: require("../../assets/course/bio.jpg"),
        description: "Biology is a natural science discipline that studies living things. It is a very large and broad field due to the wide variety of life found on Earth, so individual biologists normally focus on specific fields. These fields are either categorized by the scale of life or by the types of organisms studied",
        course1: "Microorganisms",
        course2: "nervous cells",
        course3: "genes",
        price: 1500,
    },
];

export default Courses;